urls.py
from django.urls import path

from . import views

app_name = 'files'
urlpatterns = [
    path('', views.index, name='filesindex'),
    path('folder/<int:folder_id>/', views.folder, name='folder'),
    path('folder/<int:folder_id>/edit/', views.folder_edit, name='folder_edit'),
    path('file/<int:file_id>/', views.file, name='file'),
    path('<slug:slug>/', views.path, name="path"),
    path('<slug:slug>/<path:path>', views.path, name="path"),
    path('<slug:slug>/<path:path>.html', views.path, name="filewrapper"),
    path('<slug:slug>/<path:ppath>/<path:path>.html', views.path, name="filewrapper")
]

templates/files/file.html
<div>
    <a href="{% url 'files:path' file.parent.slug file.parent.relpath %}">&lArr; {{file.parent.name}}</a>
</div>

<a href="{{file.url}}">{{file.url}}</a>

templates/files/folder.html
{% extends "index/base.html" %}
{% block body %}
{% load humanize %}
{% load indextags %}
<h2>{{folder.name}}</h2>
<div id="descriptiondiv" class="toggle" style="position: relative">
{% if folder.description %}<div id="description" class="toggle-normal">{{folder.description|markdown}}<div class="toggle-handle" style="position: absolute; right: 0; bottom: 0"><span class="glyphicon glyphicon-pencil" style="float: right; position: relative; top: -1em"> </span></div></div>{% endif %}


<form class="toggle-alternative" action="{% url 'files:folder_edit' folder.id %}" method="post">
    <textarea id="description_edit" name="description" style="width: 100%">{{folder.description}}</textarea>
    <input type="submit" value="save">
    <span class="glyphicon glyphicon-remove toggle-handle" style="float: right; position: relative; top: -1em"> </span>
    {% csrf_token %}
</form>
</div>
<style>
.toggle .toggle-normal {
    display: block;
}
.toggle .toggle-alternative {
    display: none;
}
.toggle.toggle-active .toggle-normal {
    display: none;
}
.toggle.toggle-active .toggle-alternative {
    display: block;
}
.footer { margin-top: 5em; }
.footer a {
    color: gray;
    text-decoration: none;
}
</style>

<table>
    <thead>
        <th>Name</th>
        <th>Last modified</th>
        <th>Size</th>
        <th>Type</th>
    </thead>

    <tbody>

{% if folder.parent %}
<tr>
    <td><a href="{{ folder.parent.default_url }}">..</a></td>
    <td colspan=3></td>
</tr>
{% endif %}

<!--  for f in folder.files.all -->
{% for base, items in gg %}
<tr>
    <td colspan="4">{% if items.0.file.get_thumb %}<img src="{{items.0.file.get_thumb.url}}" />{%endif%} <a href="{% url 'files:path' items.0.file.slug items.0.file.relbase %}">{{base}}</a> {% for d in items %}<a href="{% url 'files:path' d.file.slug d.file.relpath %}">{{d.ext}}</a>{% endfor %}</td>
    
<!--     <td>{{f.last_modified|naturaltime}}</td>
    <td>{{f.content_length|filesizeformat}}</td>
    <td>{{f.content_type}}</td>
 -->
</tr>
{%endfor%}

{% for f in folder.subfolders.all %}
<tr>
    <td><a href="{% url 'files:path' f.slug f.relpath %}">{{f.name}}</a></td>
    <td>{{f.last_modified|naturaltime}}</td>
    <td>&mdash;</td>
    <td>directory</td>
</tr>
{%endfor%}

    </tbody>
</table>

<div class="footer url">Source: <a href="{{folder.url}}">{{folder.url}}</a></div>

{% endblock %}

templates/files/index.html
<ul>
{% for f in folders %}
<li><a href="{% url 'files:folder' f.id %}">{{f.local_url}}</a></li>
{%endfor%}
</ul>

templates/files/media.html
{% extends "index/base.html" %}
{% block body %}
{% load indextags %}
<style>
.footer { margin-top: 5em; }
.footer a {
    color: gray;
    text-decoration: none;
}
video, audio {
    width: 100%;
}
</style>
<h2>{{base}}</h2>

{% if type == 'video' %}
<video controls>
    {% for f in media %}
    <source src="{{f.url}}" type="{{f.content_type}}" />
    {% endfor %}
</video>
{% elif type == 'audio' %}
<audio controls>
    {% for f in media %}
    <source src="{{f.url}}" type="{{f.content_type}}" />
    {% endfor %}
</audio>
{% endif %}

<!-- parent -->
<h5><a href="{% url 'files:path' file.parent.slug file.parent.relpath %}">{{file.parent.name}}</a></h5>
<div>{{file.parent.description|markdown}}</div>

<div class="footer">Sources:
    <ul>
    {% for f in media %}
    <li><a href="{{f.url}}">{{f.url}}</a></li>
    {% endfor %}
    </ul>
</div>

{% endblock %}